services:

  _defaults:
    public: false
    autowire: true

  Projekteins\GraphQL\Mutator\:
    resource: 'src/*'
    exclude: 'src/**/{DataType,Exception,Shop,Event,Subscriber}'
    public: true

  Projekteins\GraphQL\Mutator\Shared\Service\NamespaceMapper:
      class: Projekteins\GraphQL\Mutator\Shared\Service\NamespaceMapper
      tags: ['graphql_namespace_mapper']
